module.exports = {
  name: 'Patagonia Electric',
  legalName: 'Patagonia Eléctric',
  tagline: 'Ingeniería y Montaje Eléctrico',
  description: 'Equipo multidisciplinario experto en ingeniería eléctrica y automatización industrial con resultados garantizados.',
  url: process.env.SITE_URL || 'https://www.patagoniaelectric.com',
  email: 'contacto@patagoniaelectric.com',
  phone: '+56 9 6227 4047',
  phoneRaw: '+56962274047',
  whatsapp: '56962274047',
  address: {
    street: 'Frutillar',
    city: 'Frutillar',
    region: 'Región de los Lagos',
    country: 'Chile',
    countryCode: 'CL',
  },
  geo: {
    latitude: -41.1267,
    longitude: -73.065,
  },
  hours: 'Lunes a Viernes 08:30 a 18:00',
  openingHours: 'Mo-Fr 08:30-18:00',
  foundedYear: 2014,
  defaultKeywords: [
    'Patagonia Electric',
    'ingeniería eléctrica',
    'automatización industrial',
    'instalaciones eléctricas',
    'montaje eléctrico',
    'tableros eléctricos',
    'proyectos eléctricos Chile',
    'electricista Frutillar',
    'empresa eléctrica Los Lagos',
    'certificaciones técnicas',
    'garantía al cliente',
    'equipo multidisciplinario',
    'paneles solares Chile',
    'media tensión',
    'mantenimiento eléctrico industrial',
  ],
};
